#!/usr/bin/env python3
"""Phase 7 — generate platform/sdlc/13_skills/MASTER_INDEX.md.

Single source of truth for skill discovery. Grouped by provenance band
(native/migrated/external), with secondary grouping by domain. Includes
tier, layer, runtime targets, perfection score (when telemetry exists).

Modes:
  --check   Compare existing MASTER_INDEX.md to generated output; exit 1 if drift
  --output PATH   Write to a custom location (default: MASTER_INDEX.md)
  --json    Emit JSON sidecar (MASTER_INDEX.json) for atlas_skill_list MCP tool
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[3]
ACTIVE_DIR = REPO_ROOT / "platform" / "sdlc" / "13_skills" / "active"
DEFAULT_OUTPUT = REPO_ROOT / "platform" / "sdlc" / "13_skills" / "MASTER_INDEX.md"
JSON_OUTPUT = REPO_ROOT / "platform" / "sdlc" / "13_skills" / "MASTER_INDEX.json"


def kebab_from_canonical_id(canonical_id: str) -> str:
    m = re.match(r"^SKILL_(.+)_\d{3}$", canonical_id)
    if not m:
        return canonical_id.lower().replace("_", "-")
    return m.group(1).lower().replace("_", "-")


def perfection_score(im: dict[str, Any] | None) -> float | None:
    if not im or not isinstance(im, dict):
        return None
    cp100 = im.get("corrections_per_100_uses")
    if cp100 is None:
        invocations = im.get("invocation_count", 0)
        return None if invocations == 0 else 1.0
    return round(1.0 / (1.0 + float(cp100)), 4)


def collect_skills() -> list[dict[str, Any]]:
    skills: list[dict[str, Any]] = []
    for p in sorted(ACTIVE_DIR.glob("SKILL_*.yaml")):
        d = yaml.safe_load(p.read_text()) or {}
        if not d.get("id"):
            continue
        sn = d.get("skill_number")
        if isinstance(sn, str) and sn.isdigit():
            sn = int(sn)
        skills.append(
            {
                "id": d["id"],
                "title": d.get("title", ""),
                "version": d.get("version", ""),
                "tier": d.get("tier", ""),
                "layer": d.get("layer", ""),
                "status": d.get("status", ""),
                "source": d.get("source", ""),
                "skill_number": sn if isinstance(sn, int) else None,
                "domains": d.get("domains") or [],
                "aliases": d.get("aliases") or [],
                "runtime_projection": d.get("runtime_projection", True),
                "runtime_projection_targets": d.get(
                    "runtime_projection_targets", ["claude", "codex", "gemini"]
                ),
                "kebab": (
                    (d.get("aliases") or [None])[0]
                    or kebab_from_canonical_id(d["id"])
                ),
                "perfection_score": perfection_score(d.get("improvement_metrics")),
                "playbook_path": d.get("playbook"),
            }
        )
    return skills


def band_for(sn: int | None) -> str:
    if sn is None:
        return "unknown"
    if 1 <= sn <= 499:
        return "native (1-499)"
    if 500 <= sn <= 999:
        return "migrated_user (500-999)"
    if 1000 <= sn <= 1999:
        return "promoted_external (1000-1999)"
    return "reserved (2000+)"


def render_markdown(skills: list[dict[str, Any]]) -> str:
    today = dt.date.today().isoformat()
    by_band: dict[str, list[dict]] = defaultdict(list)
    by_domain_band: dict[tuple[str, str], list[dict]] = defaultdict(list)
    tier_counts: dict[str, int] = defaultdict(int)
    layer_counts: dict[str, int] = defaultdict(int)

    for s in skills:
        b = band_for(s["skill_number"])
        by_band[b].append(s)
        for dom in s["domains"] or ["(none)"]:
            by_domain_band[(dom, b)].append(s)
        tier_counts[s["tier"] or "(none)"] += 1
        layer_counts[s["layer"] or "(none)"] += 1

    lines: list[str] = []
    lines.append("# Master Skill Index")
    lines.append("")
    lines.append(f"**Generated:** {today}")
    lines.append(f"**Total skills:** {len(skills)}")
    lines.append("**Authority:** auto-generated by "
                 "`infrastructure/scripts/skill_index/generate_master_index.py`")
    lines.append("**Do not hand-edit.** Edit the canonical SKILL_*.yaml files and regenerate.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Provenance bands**")
    for b in sorted(by_band):
        lines.append(f"  - {b}: {len(by_band[b])}")
    lines.append(f"- **Tiers**")
    for t in sorted(tier_counts):
        lines.append(f"  - {t}: {tier_counts[t]}")
    lines.append(f"- **Layers**")
    for l in sorted(layer_counts):
        lines.append(f"  - {l}: {layer_counts[l]}")
    lines.append("")
    lines.append("## Discovery")
    lines.append("")
    lines.append("- **By kebab name (runtime invocation):** `/<kebab>` in any of Claude / Codex / Gemini")
    lines.append("- **By canonical ID:** `mcp__atlas__atlas_skill_get(<SKILL_ID>)`")
    lines.append("- **By domain/tier filter:** `mcp__atlas__atlas_skill_list(domain=<...>, tier=<...>)`")
    lines.append("")
    lines.append("## Skills by Provenance Band")
    lines.append("")

    for band in sorted(by_band):
        lines.append(f"### {band}")
        lines.append("")
        lines.append("| skill_number | id | tier | layer | domains | kebab |")
        lines.append("|---:|---|---|---|---|---|")
        for s in sorted(by_band[band], key=lambda x: x["skill_number"] or 9999):
            sn = s["skill_number"] if s["skill_number"] is not None else "?"
            doms = ", ".join(s["domains"][:3]) + (
                "..." if len(s["domains"]) > 3 else ""
            )
            lines.append(
                f"| {sn} | `{s['id']}` | {s['tier']} | {s['layer']} | {doms} | `{s['kebab']}` |"
            )
        lines.append("")

    lines.append("## See Also")
    lines.append("")
    lines.append("- [TAXONOMY.md](TAXONOMY.md) — controlled vocabulary")
    lines.append("- [LIFECYCLE.md](LIFECYCLE.md) — promotion/demotion contract")
    lines.append("- [skills.registry.yaml](skills.registry.yaml) — machine-readable registry")
    lines.append(
        "- `infrastructure/scripts/validate_skill_router_integration.py` — sacred invariant gate"
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    skills = collect_skills()
    md = render_markdown(skills)
    js = {
        "generated": dt.date.today().isoformat(),
        "total": len(skills),
        "skills": skills,
    }

    if args.check:
        if not args.output.exists():
            print(f"FAIL: {args.output} missing", file=sys.stderr)
            return 1
        existing = args.output.read_text()
        # Date-insensitive comparison: the **Generated:** line carries today's date, which
        # would make --check report drift every day after the file is committed (a flaky CI
        # gate). Normalize that one volatile line so --check reflects real content drift only.
        norm = lambda s: re.sub(r"(?m)^\*\*Generated:\*\* .*$", "**Generated:** <date>", s)
        if norm(existing) != norm(md):
            print(f"DRIFT: {args.output.relative_to(REPO_ROOT)} differs from generated", file=sys.stderr)
            return 1
        print("PASS: master index in sync")
        return 0

    args.output.write_text(md)
    print(f"Wrote: {args.output.relative_to(REPO_ROOT)}  ({len(skills)} skills)")
    if args.json:
        JSON_OUTPUT.write_text(json.dumps(js, indent=2, default=str))
        print(f"Wrote: {JSON_OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
