#!/usr/bin/env python3
"""
derive_gate_state.py — production-readiness.ts release state is DERIVED from probes,
never hand-typed.

The false-completion hole: production-readiness.ts hardcoded
`releaseRecommendation: "READY_FOR_PUBLIC_RELEASE"` for a read-only demo, and CI
asserted against that hand-typed string — so CI passed a lie. Fix: the value is
COMPUTED from probe_results.json. Hand-editing it to a different string just
recreates the hole, so `--check` fails whenever the committed .ts disagrees with
what the probes derive.

Rules:
  - If the probe suite has ANY fail/unknown  -> releaseRecommendation = "BLOCK_PUBLIC_RELEASE"
  - Only if every probe passes               -> "READY_FOR_PUBLIC_RELEASE"
  The derived value + a generated evidence block live between sentinel markers so
  this script (not a human) owns them.

Usage:
  python3 derive_gate_state.py --write    # run probes, write derived state into the .ts
  python3 derive_gate_state.py --check     # FAIL (exit 1) if committed .ts != derived state
  python3 derive_gate_state.py --print     # show derived recommendation, no writes
"""
from __future__ import annotations
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]            # ATLAS repo root
PRT = ROOT / "apps" / "frontend" / "shell" / "src" / "lib" / "production-readiness.ts"
PROBE_RUNNER = ROOT / "platform" / "systems" / "53_production_readiness" / "probes" / "probe_runner.py"
PROBE_RESULTS = ROOT / "platform" / "systems" / "53_production_readiness" / "probes" / "results" / "probe_results.json"

BEGIN = "// <derived-gate-state> GENERATED by infrastructure/scripts/production_readiness/derive_gate_state.py — DO NOT EDIT BY HAND"
END = "// </derived-gate-state>"


def run_probes() -> dict:
    """Run the HERMETIC probe subset fresh (the source of truth), fall back to last results file.

    --hermetic is deterministic from committed repo files (no node / no live host), so this
    derivation yields the SAME committed gate state in CI and local — the fix for the perpetual
    --check DRIFT (audit #13). Runtime probes (node verify scripts, launchctl, HTTP) are gated
    separately in CI and never feed the committed block."""
    try:
        out = subprocess.run([sys.executable, str(PROBE_RUNNER), "--json", "--hermetic"],
                             capture_output=True, text=True, timeout=180)
        if out.stdout.strip():
            return json.loads(out.stdout)
    except Exception:
        pass
    if PROBE_RESULTS.exists():
        return json.loads(PROBE_RESULTS.read_text())
    raise SystemExit("derive_gate_state: cannot run probes or read probe_results.json")


def derive(report: dict) -> dict:
    # The committed gate state is governed ONLY by HERMETIC probes. If the report is the full
    # suite (e.g. the probe_results.json fallback), filter to hermetic here so the derivation is
    # environment-independent regardless of source. Each result carries its tier (run_all stamps it).
    results = report.get("results", [])
    hermetic = [r for r in results if r.get("tier") == "hermetic"]
    governed = hermetic if hermetic else results  # tolerate legacy untagged results
    failed = [r for r in governed if r["verdict"] != "pass"]
    all_pass = not failed
    rec = "READY_FOR_PUBLIC_RELEASE" if all_pass else "BLOCK_PUBLIC_RELEASE"
    reasons = [f"{r['id']}:{r['verdict']}" for r in failed]
    gov_summary = {"pass": 0, "fail": 0, "unknown": 0}
    for r in governed:
        gov_summary[r["verdict"]] = gov_summary.get(r["verdict"], 0) + 1
    return {
        "releaseRecommendation": rec,
        "derivedBy": "infrastructure/scripts/production_readiness/derive_gate_state.py",
        "governedBy": "hermetic",  # fingerprint: which probe tier governs the committed state
        "hermeticProbes": sorted(r["id"] for r in governed),
        "probeSummary": gov_summary,
        "blockingProbes": reasons,
    }


def derived_block(d: dict) -> str:
    body = json.dumps(d, indent=2)
    body = "\n".join("  " + ln for ln in body.splitlines())
    return (f"{BEGIN}\n"
            f"export const atlasDerivedGateState = {body.strip()} as const;\n"
            f"export const atlasReleaseRecommendation = atlasDerivedGateState.releaseRecommendation;\n"
            f"{END}")


def current_block(txt: str) -> str | None:
    m = re.search(re.escape(BEGIN) + r".*?" + re.escape(END), txt, re.DOTALL)
    return m.group(0) if m else None


def apply_block(txt: str, block: str) -> str:
    existing = current_block(txt)
    if existing:
        return txt.replace(existing, block)
    return txt.rstrip() + "\n\n" + block + "\n"


def sync_recommendation_line(txt: str, rec: str) -> str:
    """Also force the hand-typed releaseRecommendation field to match the derived value,
    so the legacy field can never disagree with probes."""
    return re.sub(r'(releaseRecommendation:\s*)"[^"]*"', rf'\1"{rec}"', txt, count=1)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--print", dest="show", action="store_true")
    args = ap.parse_args()

    report = run_probes()
    d = derive(report)
    block = derived_block(d)

    if args.show or not (args.write or args.check):
        print(json.dumps(d, indent=2))
        return 0

    txt = PRT.read_text(encoding="utf-8")
    desired = apply_block(sync_recommendation_line(txt, d["releaseRecommendation"]), block)

    if args.check:
        if txt != desired:
            cur = current_block(txt)
            print("DRIFT: production-readiness.ts release state DISAGREES with probe-derived state.")
            print(f"  derived releaseRecommendation = {d['releaseRecommendation']}")
            print(f"  blocking probes = {d['blockingProbes']}")
            if cur is None:
                print("  (no derived-gate-state block present — run --write)")
            print("  fix: python3 infrastructure/scripts/production_readiness/derive_gate_state.py --write")
            return 1
        print(f"OK: production-readiness.ts matches probe-derived state ({d['releaseRecommendation']}).")
        return 0

    # --write
    PRT.write_text(desired, encoding="utf-8")
    print(f"WROTE derived state: releaseRecommendation = {d['releaseRecommendation']}; "
          f"blocking probes = {d['blockingProbes']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
