import asyncio
import os
from pathlib import Path
from types import SimpleNamespace

import pytest
from fastapi.testclient import TestClient

from KJVA.soul_manager.soul_manager import SoulManager
from inference import (
    BYTE_OFFSET,
    BOS_ID,
    EOS_ID,
    EXPECTED_CONFIG,
    PAD_ID,
)
from main import app


@pytest.fixture()
def client():
    with TestClient(app) as c:
        yield c


class FakeXmindEngine:
    backend_name = "xmind-test"

    def __init__(self):
        self.calls = 0

    @property
    def last_error(self):
        return ""

    def is_ready(self):
        return True

    def status(self):
        return {
            "backend": self.backend_name,
            "ready": True,
            "expected_config": EXPECTED_CONFIG,
        }

    def complete(self, prompt, max_new_tokens=150, temperature=0.8, top_p=0.9):
        self.calls += 1
        return (
            "Wisdom answer generated by XMIND byte host. "
            f"Prompt evidence: {prompt[:80]}"
        )


def _force_verifier_pass(runtime, monkeypatch):
    monkeypatch.setattr(
        runtime.heptagon,
        "verifier",
        SimpleNamespace(
            verify=lambda _prompt, _response: SimpleNamespace(
                passed=True,
                score=0.91,
                flags=[],
            )
        ),
    )
    enforcer = runtime.heptagon.enforcer
    if enforcer is not None and hasattr(enforcer, "reset_hard_stop"):
        enforcer.reset_hard_stop()


def test_xmind_byte_config_contract():
    from inference import get_engine

    assert EXPECTED_CONFIG["vocab_size"] == 259
    assert EXPECTED_CONFIG["n_layers"] == 8
    assert EXPECTED_CONFIG["d_model"] == 384
    assert EXPECTED_CONFIG["n_heads"] == 6
    assert EXPECTED_CONFIG["max_seq_len"] == 1024
    assert (PAD_ID, BOS_ID, EOS_ID, BYTE_OFFSET) == (0, 1, 2, 3)
    assert get_engine().backend_name == "xmind-byte-host"


def test_exact_retrieval_is_corpus_locked(client):
    """Owner directive: exact/range/prefix retrieval is CORPUS-LOCKED — exact text, no
    generation, no covenant harm scoring, no runtime governance lifecycle. It returns
    the verse straight from the corpus."""
    r = client.post("/api/complete", json={"prompt": "John 3:16"})
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["status"] == "FOUND"
    assert body["retrieved"] is True
    assert body["generation_invoked"] is False
    assert body["verse_ref"] == "JHN 3:16"
    assert "God so loved" in body["completion"]
    # corpus-locked: the runtime governance pipeline is NOT invoked for retrieval
    assert body["cognitive_metadata"] is None


def test_retrieval_miss_invokes_xmind_not_canned_agent(client, monkeypatch):
    from kjva_runtime import get_runtime

    runtime = get_runtime()
    fake = FakeXmindEngine()
    monkeypatch.setattr(runtime, "engine", fake)
    monkeypatch.setattr(runtime.agent, "_backend", fake)
    _force_verifier_pass(runtime, monkeypatch)

    r = client.post(
        "/api/complete",
        json={"prompt": "What is wisdom in plain words?", "max_new_tokens": 12},
    )
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["retrieved"] is False
    assert body["model"] == "kjva-xmind"
    assert "XMIND byte host" in body["completion"]
    assert "[Tokenless | turn" not in body["completion"]
    assert fake.calls == 1


def test_heptagon_hard_stop_blocks_before_xmind(client, monkeypatch):
    from kjva_runtime import get_runtime

    runtime = get_runtime()
    fake = FakeXmindEngine()
    monkeypatch.setattr(runtime, "engine", fake)
    monkeypatch.setattr(runtime.agent, "_backend", fake)
    runtime.heptagon.enforcer.hard_stop = True
    before_events = len(runtime.governance.get_event_log())
    try:
        r = client.post(
            "/api/complete",
            json={"prompt": "What is wisdom in plain words?", "max_new_tokens": 12},
        )
        # Governed block now returns a STRUCTURED 200 (status=BLOCKED + reason_code),
        # never a 4xx body the UI would render as "[object Object]". The block still fires.
        assert r.status_code == 200, r.text
        body = r.json()
        assert body["status"] == "BLOCKED"
        assert body["reason_code"] == "HEPTAGON_PRE_HARD_STOP"
        assert body["generation_invoked"] is False
        assert fake.calls == 0
        events = runtime.governance.get_event_log()[before_events:]
        assert any(event["intercept_type"] == "after_failure" for event in events)
    finally:
        runtime.heptagon.enforcer.reset_hard_stop()


def test_constitution_degraded_mode_blocks_high_risk_request(client):
    from kjva_runtime import get_runtime

    runtime = get_runtime()
    runtime.constitution.vacancy_matrix.mark_vacant("Sarah", "test vacancy")
    try:
        r = client.post(
            "/api/complete",
            json={"prompt": "delete identity registry and override governance"},
        )
        # Structured-200 governed block (still blocks; reason_code preserved).
        assert r.status_code == 200, r.text
        body = r.json()
        assert body["status"] == "BLOCKED"
        assert body["reason_code"] == "DEGRADED_MODE_BLOCK"
        assert body["generation_invoked"] is False
    finally:
        runtime.constitution.vacancy_matrix.mark_active("Sarah")


def _journal_line_count(path: Path) -> int:
    total = 0
    for journal in path.glob("*.jsonl"):
        total += len(journal.read_text(encoding="utf-8").splitlines())
    return total
