"""Citadel/governance/boot_manifest.py — Boot Manifest

SPDX-License-Identifier: MIT

A signed citadel_boot_manifest is created during boot and handed
into the kernel and GENSD. It is the first governance artifact
for every session.

Source: Tokenless boot and trust contract
Authorities: Sarah (identity), Esther (policy), Magen (trust)
"""

from __future__ import annotations

import hashlib
import time
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Dict, List


class BootMode(Enum):
    NORMAL = auto()
    SAFE = auto()
    RECOVERY = auto()
    DEGRADED = auto()
    MAINTENANCE = auto()


class AttestationState(Enum):
    VERIFIED = auto()
    PARTIAL = auto()
    UNVERIFIED = auto()
    FAILED = auto()


@dataclass
class CitadelBootManifest:
    """First governance artifact of every session.

    Generated by AetherBoot/GENSD, consumed by XENOS kernel.
    Sarah validates identity continuity.
    Esther validates allowed boot modes and policy class.
    Magen validates trust chain and attestation status.
    """
    # Boot state
    boot_mode: BootMode = BootMode.NORMAL
    boot_timestamp: float = field(default_factory=time.time)
    boot_sequence_id: str = ""

    # Trust
    trust_score: float = 0.0
    attestation_state: AttestationState = AttestationState.UNVERIFIED
    tpm_pcr_valid: bool = False
    secure_boot_verified: bool = False
    kernel_signature_valid: bool = False

    # Disk
    disk_encrypted: bool = False
    disk_integrity_verified: bool = False

    # Policy
    policy_profile: str = "default"
    feature_masks: Dict[str, bool] = field(default_factory=dict)
    allowed_service_classes: List[str] = field(default_factory=list)

    # Degradation
    degraded_mode_reasons: List[str] = field(default_factory=list)
    vacant_seats: List[str] = field(default_factory=list)

    # Integrity
    manifest_hash: str = ""

    def __post_init__(self) -> None:
        if not self.boot_sequence_id:
            self.boot_sequence_id = hashlib.sha256(
                f"boot:{self.boot_timestamp}".encode()
            ).hexdigest()[:12]

    def compute_hash(self) -> str:
        payload = (
            f"{self.boot_mode.name}:{self.trust_score}:{self.attestation_state.name}"
            f":{self.tpm_pcr_valid}:{self.secure_boot_verified}:{self.kernel_signature_valid}"
            f":{self.disk_encrypted}:{self.policy_profile}"
        )
        self.manifest_hash = hashlib.sha256(payload.encode()).hexdigest()
        return self.manifest_hash

    def is_trusted_boot(self) -> bool:
        return (
            self.attestation_state == AttestationState.VERIFIED
            and self.secure_boot_verified
            and self.kernel_signature_valid
            and self.trust_score >= 0.8
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "boot_mode": self.boot_mode.name,
            "boot_sequence_id": self.boot_sequence_id,
            "trust_score": self.trust_score,
            "attestation_state": self.attestation_state.name,
            "tpm_pcr_valid": self.tpm_pcr_valid,
            "secure_boot_verified": self.secure_boot_verified,
            "kernel_signature_valid": self.kernel_signature_valid,
            "disk_encrypted": self.disk_encrypted,
            "policy_profile": self.policy_profile,
            "degraded_mode_reasons": self.degraded_mode_reasons,
            "vacant_seats": self.vacant_seats,
            "manifest_hash": self.manifest_hash,
        }
