#!/usr/bin/env python3
"""Phase 6 — Generate runtime projection shims for Claude / Codex / Gemini.

Reads every canonical SKILL_*.yaml in platform/sdlc/13_skills/active/ and
projects it into up to three runtime locations based on its
`runtime_projection_targets` field (default: [claude, codex, gemini]).

Projection layout:

  Claude  : ~/.claude/skills/<kebab>/SKILL.md
  Codex   : ~/.codex/skills/<kebab>/SKILL.md      + ~/.codex/commands/<kebab>.md
  Gemini  : ~/.gemini/commands/<kebab>.md

The kebab name is:
  1. aliases[0] (first preferred alias)  if set
  2. derived from canonical id (SKILL_FOO_BAR_001 -> foo-bar)

Each generated shim:
  - Has frontmatter with name, description, source path, canonical_id,
    generated date, runtime tag
  - Contains a banner explaining it is a generated projection
  - Embeds the FULL canonical playbook body (single source of truth)
  - Adds a post-invocation telemetry hook comment (Phase 8 anchor)

Skills with runtime_projection: false are skipped entirely (no shims).
Skills with runtime_projection_targets: [...] are projected only to listed runtimes.

Before regenerating, the existing projection roots are backed up to
backups/runtime_projections_<date>.tar.gz (gitignored).

Modes:
  --dry-run         Preview counts, no writes
  --apply           Regenerate
  --no-backup       Skip the safety backup (default: backup)
  --no-delete       Keep orphans; default deletes shims for skills not in canonical
  --targets <list>  Only project to listed runtimes (default: from skill yaml)
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[3]
ACTIVE_DIR = REPO_ROOT / "platform" / "sdlc" / "13_skills" / "active"
HOME = Path.home()

CLAUDE_SKILLS = HOME / ".claude" / "skills"
CODEX_SKILLS = HOME / ".codex" / "skills"
CODEX_COMMANDS = HOME / ".codex" / "commands"
GEMINI_COMMANDS = HOME / ".gemini" / "commands"

DEFAULT_TARGETS = ["claude", "codex", "gemini"]

TODAY = dt.date.today().isoformat()


def kebab_from_canonical_id(canonical_id: str) -> str:
    """SKILL_FOO_BAR_001 -> foo-bar."""
    m = re.match(r"^SKILL_(.+)_\d{3}$", canonical_id)
    if not m:
        return canonical_id.lower().replace("_", "-")
    return m.group(1).lower().replace("_", "-")


def derive_kebab(data: dict[str, Any], used_kebabs: set[str] | None = None) -> str:
    """Derive kebab name; disambiguate if used_kebabs already contains the preference."""
    aliases = data.get("aliases") or []
    canonical_kebab = kebab_from_canonical_id(data.get("id", ""))

    preferred = aliases[0] if aliases and isinstance(aliases[0], str) else canonical_kebab

    if used_kebabs is None:
        return preferred

    # If preferred is free, take it
    if preferred not in used_kebabs:
        return preferred

    # If preferred is taken but the canonical-derived kebab is different and free, use it
    if canonical_kebab != preferred and canonical_kebab not in used_kebabs:
        return canonical_kebab

    # Both taken — disambiguate by appending the numeric portion of the skill_number
    sn = data.get("skill_number") or 0
    candidate = f"{preferred}-{sn}"
    if candidate not in used_kebabs:
        return candidate

    # Last resort: append the full id
    return f"{preferred}-{data.get('id', 'unknown').lower().replace('_', '-')}"


def read_playbook(canonical_id: str) -> str:
    path = ACTIVE_DIR / f"{canonical_id}.playbook.md"
    if not path.exists():
        return f"<!-- canonical playbook missing for {canonical_id} -->\n"
    return path.read_text()


def derive_description(data: dict[str, Any], playbook_body: str) -> str:
    """Title + first non-empty content line as description."""
    title = data.get("title") or data.get("id", "")
    # Find first content line (skip headers, comments, blockquotes)
    for line in playbook_body.splitlines():
        s = line.strip()
        if not s or s.startswith("#") or s.startswith("<!--") or s.startswith(">"):
            continue
        if s.startswith("**Summary."):
            s = s[len("**Summary.") :].strip().rstrip("*").strip()
        return f"{title} — {s[:160]}"
    return title


def claude_shim(data: dict[str, Any], kebab: str, playbook_body: str) -> str:
    description = derive_description(data, playbook_body)
    return f"""---
name: {kebab}
description: {yaml_quote(description)}
source: platform/sdlc/13_skills/active/{data['id']}.yaml
canonical_id: {data['id']}
generated: {TODAY}
runtime: claude_code
---

> **Runtime projection of `{data['id']}`.** Edit the canonical, not this file.
> Source of truth: `platform/sdlc/13_skills/active/{data['id']}.playbook.md`
> Regenerated by: `infrastructure/scripts/skill_projection/generate_runtime_shims.py`

{playbook_body.rstrip()}

<!-- POST-INVOCATION TELEMETRY HOOK (Phase 8) -->
<!-- This skill emits telemetry on invocation via ~/.claude/hooks/post_skill.sh -->
<!-- See: infrastructure/scripts/skill_refinement/capture_invocation.py -->
"""


def codex_shim(data: dict[str, Any], kebab: str, playbook_body: str) -> str:
    description = derive_description(data, playbook_body)
    return f"""---
name: {kebab}
description: {yaml_quote(description)}
source: platform/sdlc/13_skills/active/{data['id']}.yaml
canonical_id: {data['id']}
generated: {TODAY}
runtime: codex
---

> **Runtime projection of `{data['id']}`.** Edit the canonical, not this file.
> Source of truth: `platform/sdlc/13_skills/active/{data['id']}.playbook.md`

{playbook_body.rstrip()}
"""


def codex_command(data: dict[str, Any], kebab: str, playbook_body: str) -> str:
    description = derive_description(data, playbook_body)
    return f"""---
name: {kebab}
description: {yaml_quote(description)}
canonical_id: {data['id']}
generated: {TODAY}
runtime: codex
invocation: slash_command
---

{playbook_body.rstrip()}
"""


def gemini_command(data: dict[str, Any], kebab: str, playbook_body: str) -> str:
    description = derive_description(data, playbook_body)
    return f"""---
name: {kebab}
description: {yaml_quote(description)}
canonical_id: {data['id']}
generated: {TODAY}
runtime: gemini
invocation: slash_command
---

{playbook_body.rstrip()}
"""


def yaml_quote(s: str) -> str:
    """Quote a string for inclusion as a YAML frontmatter scalar.

    Removes characters that break YAML scalar parsing in shim consumers.
    """
    s = s.replace("\n", " ").replace("\r", " ").strip()
    if not s:
        return '""'
    if any(c in s for c in (":", "#", "{", "}", "[", "]", ",", "&", "*", "?", "|", ">", "!", "%", "@", "`", '"')):
        # Use double quotes with escaping
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return s


def make_backup(dry_run: bool) -> Path | None:
    if dry_run:
        return None
    backup_dir = REPO_ROOT / "backups"
    backup_dir.mkdir(exist_ok=True)
    backup_path = backup_dir / f"runtime_projections_{TODAY}.tar.gz"
    roots: list[str] = []
    for r in (CLAUDE_SKILLS, CODEX_SKILLS, CODEX_COMMANDS, GEMINI_COMMANDS):
        if r.exists():
            roots.append(str(r))
    if not roots:
        return None
    subprocess.run(
        ["tar", "-czf", str(backup_path), *roots],
        check=False,
        capture_output=True,
    )
    return backup_path if backup_path.exists() else None


def collect_canonical_skills() -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for p in sorted(ACTIVE_DIR.glob("SKILL_*.yaml")):
        d = yaml.safe_load(p.read_text()) or {}
        if not d.get("id"):
            continue
        out.append(d)
    return out


def project_for_skill(
    data: dict[str, Any],
    targets_override: list[str] | None,
    dry_run: bool,
    used_kebabs: set[str] | None = None,
) -> tuple[dict[str, int], str]:
    """Project one skill to its enabled runtimes. Returns (counts, kebab_used)."""
    counts = {"claude": 0, "codex_skill": 0, "codex_command": 0, "gemini": 0}
    if data.get("runtime_projection") is False:
        return counts, ""

    targets = (
        targets_override
        if targets_override is not None
        else (data.get("runtime_projection_targets") or DEFAULT_TARGETS)
    )

    canonical_id = data["id"]
    kebab = derive_kebab(data, used_kebabs)
    playbook_body = read_playbook(canonical_id)

    if "claude" in targets:
        dest = CLAUDE_SKILLS / kebab / "SKILL.md"
        if not dry_run:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(claude_shim(data, kebab, playbook_body))
        counts["claude"] = 1

    if "codex" in targets:
        dest_skill = CODEX_SKILLS / kebab / "SKILL.md"
        dest_cmd = CODEX_COMMANDS / f"{kebab}.md"
        if not dry_run:
            dest_skill.parent.mkdir(parents=True, exist_ok=True)
            dest_cmd.parent.mkdir(parents=True, exist_ok=True)
            dest_skill.write_text(codex_shim(data, kebab, playbook_body))
            dest_cmd.write_text(codex_command(data, kebab, playbook_body))
        counts["codex_skill"] = 1
        counts["codex_command"] = 1

    if "gemini" in targets:
        dest = GEMINI_COMMANDS / f"{kebab}.md"
        if not dry_run:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(gemini_command(data, kebab, playbook_body))
        counts["gemini"] = 1

    return counts, kebab


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--no-backup", action="store_true")
    parser.add_argument("--no-delete", action="store_true",
                        help="Do not delete orphan shims (default: delete)")
    parser.add_argument("--targets", default=None,
                        help="Comma-separated subset of [claude,codex,gemini]")
    args = parser.parse_args()
    if not args.dry_run and not args.apply:
        print("ERROR: specify --dry-run or --apply", file=sys.stderr)
        return 2

    targets_override = (
        [t.strip() for t in args.targets.split(",")] if args.targets else None
    )

    if not args.dry_run and not args.no_backup:
        bp = make_backup(args.dry_run)
        if bp:
            print(f"Backup: {bp.relative_to(REPO_ROOT)}")
        else:
            print("Backup: (no existing projection roots to back up)")

    skills = collect_canonical_skills()
    print(f"Canonical skills: {len(skills)}")

    total = {"claude": 0, "codex_skill": 0, "codex_command": 0, "gemini": 0}
    skipped_no_projection = 0
    projected_kebabs: set[str] = set()

    for d in skills:
        if d.get("runtime_projection") is False:
            skipped_no_projection += 1
            continue
        counts, kebab = project_for_skill(d, targets_override, args.dry_run, projected_kebabs)
        for k, v in counts.items():
            total[k] += v
        if any(counts.values()) and kebab:
            projected_kebabs.add(kebab)

    # Cleanup orphans (best-effort; tolerate permission errors and nested non-skill dirs)
    orphans_removed = 0
    orphans_skipped = 0
    if not args.no_delete and not args.dry_run:
        for root, _suffix, is_dir in [
            (CLAUDE_SKILLS, "SKILL.md", True),
            (CODEX_SKILLS, "SKILL.md", True),
            (CODEX_COMMANDS, ".md", False),
            (GEMINI_COMMANDS, ".md", False),
        ]:
            if not root.exists():
                continue
            try:
                items = list(root.iterdir())
            except (PermissionError, OSError):
                continue
            for item in items:
                if is_dir:
                    if not item.is_dir():
                        continue
                    if item.name in projected_kebabs:
                        continue
                    # Skip non-kebab directories (built-in or system-managed)
                    if not item.name.replace("-", "").replace("_", "").isalnum():
                        orphans_skipped += 1
                        continue
                    try:
                        skill_md = item / "SKILL.md"
                        if skill_md.exists():
                            skill_md.unlink()
                        # Remove other files in the dir (if any)
                        try:
                            for f in item.iterdir():
                                try:
                                    f.unlink()
                                except (PermissionError, OSError):
                                    pass
                        except (PermissionError, OSError):
                            pass
                        item.rmdir()
                        orphans_removed += 1
                    except (PermissionError, OSError):
                        orphans_skipped += 1
                else:
                    if not item.is_file() or item.suffix != ".md":
                        continue
                    stem = item.stem
                    if stem in projected_kebabs:
                        continue
                    try:
                        item.unlink()
                        orphans_removed += 1
                    except (PermissionError, OSError):
                        orphans_skipped += 1

    print()
    print(f"=== Phase 6 Projection Summary ({'DRY RUN' if args.dry_run else 'APPLIED'}) ===")
    print(f"Skills with runtime_projection: false (skipped): {skipped_no_projection}")
    print(f"Claude shims (~/.claude/skills/):                {total['claude']}")
    print(f"Codex skill shims (~/.codex/skills/):            {total['codex_skill']}")
    print(f"Codex slash commands (~/.codex/commands/):       {total['codex_command']}")
    print(f"Gemini slash commands (~/.gemini/commands/):     {total['gemini']}")
    print(f"Orphan shims removed: {orphans_removed}")
    if not args.no_delete and not args.dry_run:
        print(f"Orphan shims skipped (perm-denied / built-in): {orphans_skipped}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
